### PR TITLE
chore: hoppscotch-ui improvements

### PR DESCRIPTION
**Pull request by anwarulislam**
### Description

This PR aims to improve `hoppscotch-ui` package-related issues. And fix broken things. The following issues are fixed
- Prettier fixed on `hoppscotch-common`
- `HoppSelectWrapper` component was added instead of CSS class `select-wrapper`
- `HoppCheckBox` revamped
- Remove `material-icon` dependency

### CODE REVIEW

**Comment by JoelJacobStephen** [comment]
Can you add a storybook entry for `HoppSmartSelectWrapper`?

**Review by JoelJacobStephen — CHANGES_REQUESTED** [review]
Can you add a storybook entry for `HoppSmartSelectWrapper`?

**Comment by liyasthomas** [comment]
@JoelJacobStephen the storybook component will be added to https://github.com/hoppscotch/ui package directly once these changes are in place.

**Review by liyasthomas — APPROVED** [review]
LGTM

**Review by JoelJacobStephen — APPROVED** [review]
LGTM!!

**Pull request merged**
