### PR TITLE
docs: fix broken link to .env.example in README

### PR DESCRIPTION
**Pull request by bblumenwiese**
This is my first PR for a project on public github, yay! 🥳 

Had a bit of struggle with the commitlint convention, as I didn't know this one yet - but should be fine now! Thanks in advance for review. Happy Hacktoberfest!

Refs #1852

### CODE REVIEW

**Review by liyasthomas — APPROVED** [review]
LGTM

**Comment by bblumenwiese** [comment]
Sorry, I think I made a mistake with the version number  🤦‍♀️ It should be #1853, not #1852

**Comment by liyasthomas** [comment]
@bblumenwiese no problem, it doesn't matter since it's just the description which you can actually edit.

**Comment by bblumenwiese** [comment]
I edited the PR description now but the issue reference is not clickable like in other PRs. I am not finding the issue in the issues list either, anymore. Seems like it got deleted somehow. To make things worse, I also did not get progress towards my Hacktoberfest goal. 
I will start working on other issues soon but want to make sure everything is fine with this one first.

**Pull request merged**
