### PR TITLE
feat: team search in workspace search and spotlight

### PR DESCRIPTION
**Pull request by amk-dev**
This PR introduces searching team collections & requests from the workspace sidebar and spotlight search.

### CODE REVIEW

**Review by nivedin — CHANGES_REQUESTED** [review]
- shouldn't the collection display its child folders and request while searching

https://github.com/hoppscotch/hoppscotch/assets/53208152/a78c2cc5-9fee-40f4-93b0-39a29646e33c

**Review by jamesgeorge007 — CHANGES_REQUESTED** [review]
Actions performed on the collection tree (editing, moving, etc) while a search query is present aren't immediately reflected.

**Comment by amk-dev** [comment]
> * shouldn't the collection display its child folders and request while searching

this is fixed.

**Review by jamesgeorge007 — APPROVED** [review]
LGTM 🚀
Removal of BE changes to be handled along with rebase.

**Comment by balub** [comment]
@amk-dev can you rebase this PR with the lastest changes, testing for FTS and for trigram have different edge cases I cannot test right now because the PR currently has the FTS implementation.

**Review by nivedin — CHANGES_REQUESTED** [review]
can we move the spotlight team search result to the top

https://github.com/hoppscotch/hoppscotch/assets/53208152/a65cbed4-e394-4dfe-8005-96af30461361

**Comment by AndrewBastin** [comment]
@nivedin dismissing your review as it doesn't affect the critical flow atm. this can be improved in further iterations.

**Review by nivedin — APPROVED** [review]

**Pull request merged**
