### PR TITLE
refactor: use trigram search index instead of full text search

### PR DESCRIPTION
**Pull request by AndrewBastin**
This PR intends to refactor the upcoming Team Collection Search mechanism to use Postgres Trigram Indices instead of Full Text Search for their implementation.

## What's changed
1. Updated FTS migration to setup and build trigram extension and GIN trigram indices.
2. Introduce `escapeSqlLikeString` function to create escaped strings for usage in SQL `LIKE` statements.
3.  Updated existing SQL search queries to use `ILIKE` queries instead of old FTS vector lookups.

## Notes
- Since the old migration is overwritten, you will have to start the DB again from scratch to test this as there will be mismatches between the generated DB. Due to change 1.

### CODE REVIEW

**Review by balub — DISMISSED** [review]
LGTM 🚀

**Review by mirarifhasan — COMMENTED** [review]
I think, we need to work on the response format of this API.

Somewhere, in `path` returns `array`, sometime `object`.
And, for this return format is not compatible with the existing one. Frontend might brake for this.

```
{
    "data": [
        {
            "type": "collection",
            "title": "ClickUp Level 1",
            "id": "cltse9m9s000dx4k845suw6a2",
            "path": [
                {
                    "id": "cltse8su80009x4k8iepizez8",
                    "title": "ClickUp",
                    "type": "collection",
                    "path": []
                }
            ]
        },
        {
            "type": "collection",
            "title": "ClickUp Level 2",
            "id": "cltseae9k000hx4k8enbh3yd2",
            "path": [
                {
                    "id": "cltse9m9s000dx4k845suw6a2",
                    "title": "ClickUp Level 1",
                    "type": "collection",
                    "path": {
                        "id": "cltse8su80009x4k8iepizez8",
                        "title": "ClickUp",
                        "type": "collection",
                        "path": []
                    }
                }
            ]
        },
        {
            "type": "collection",
            "title": "ClickUp",
            "id": "cltse8su80009x4k8iepizez8",
            "path": [
                null
            ]
        },
        {
            "type": "request",
            "title": "ClickUp Task Level 3",
            "method": "GET",
            "id": "cltsea86e000gx4k8wthrmqqb",
            "path": [
                {
                    "id": "cltseae9k000hx4k8enbh3yd2",
                    "title": "ClickUp Level 2",
                    "type": "collection",
                    "path": {
                        "id": "cltse9m9s000dx4k845suw6a2",
                        "title": "ClickUp Level 1",
                        "type": "collection",
                        "path": {
                            "id": "cltse8su80009x4k8iepizez8",
                            "title": "ClickUp",
                            "type": "collection",
                            "path": []
                        }
                    }
                }
            ]
        }
    ]
}
```

**Comment by balub** [comment]
@AndrewBastin The return type of path is not correct, I actually fixed this issue in my hotfix PR.

**Review by balub — APPROVED** [review]
LGTM 🚀

**Review by mirarifhasan — APPROVED** [review]

**Pull request merged**
