### PR TITLE
adding codegen for the java-unirest

### PR DESCRIPTION
**Pull request by mrkunal**
My first open-source PR :)

### CODE REVIEW

**Comment by liyasthomas** [comment]
@mrkunal can you rebase your branch to the latest or regenerate snapshot file again.

**Comment by mrkunal** [comment]
I am working on my PR merge conflict issue. Will raise the correct PR soon.

**Comment by liyasthomas** [comment]
Also you've to rebase your branch to [master](https://github.com/hoppscotch/hoppscotch/tree/master) branch.

**Review by liyasthomas — APPROVED** [review]
LGTM. Thanks for the quick PR.

Congrats on your first open source contribution :tada:
Happy hacking :heart:

**Comment by mrkunal** [comment]
Thanks @liyasthomas, Please check and approve my PR.

**Pull request merged**
