### PR TITLE
fix: show an error when pre-request script fails

### PR DESCRIPTION
**Pull request by andriuspetrauskis**
Closes https://github.com/hoppscotch/hoppscotch/issues/1980

Cleaned version of https://github.com/hoppscotch/hoppscotch/pull/1981

### CODE REVIEW

**Comment by andriuspetrauskis** [comment]
Hey @liyasthomas as you mentioned in https://github.com/hoppscotch/hoppscotch/pull/1981#issuecomment-981192683, I created this PR without lintfix changes and made it as a draft-PR.

**Comment by liyasthomas** [comment]
@andriuspetrauskis thank you for the effort, we'll be reviewing this asap.

**Review by liyasthomas — APPROVED** [review]
LGTM.

**Review by AndrewBastin — APPROVED** [review]
LGTM 💯 

Thank you for your contribution @andriuspetrauskis!!!! ❤️

**Pull request merged**
