### PR TITLE
[Feat: formData] Add chips to indicate chosen files in formData

### PR DESCRIPTION
**Pull request by nelsontky**
image

Per the image above, chips have been added to denote the files that have been chosen. This feature is still currently incomplete.

Todo:

- [x] Pressing close button on chip will lead to removal of file
- [x] Set max width of request body value field when file names are too long
- [x] Check preservation of responsive design
- [x] ~~Make sure Vuex persist works with `File` objects~~
File objects cannot be recreated, and this thus means that we will not be able to restore a user's files in a request after a reload. FormData file fields also will not be able to be synced/exported. Thus, we should exclude file fields from vuex and store them instead in a component's state.

### CODE REVIEW

**Comment by liyasthomas** [comment]
I've updated the file chip component with matching styles 🚀 

---
image

**Comment by liyasthomas** [comment]
Fixed mobile responsiveness and overflow on large file names :)

---

image

**Comment by nelsontky** [comment]
Was kinda busy at work today so didnt have much time to work on this! I should be able.to.contribute more tomorrow!

**Comment by nelsontky** [comment]
I've implemented the file deletion feature. Additionally, since `File` objects cannot be serialized nor constructed without having the bytes that make up the file itself, file inputs are excluded from all forms of persistence, namely via `vuex-persist`, via route queries, or via saving to collections.

I may have found a bug in the route queries too, in that for POST requests, the browser URL query params do not update immediately when the http body parameters are updated. I will observe the issue more and will open an issue if this issue hasn't been brought up before!

**Comment by liyasthomas** [comment]
@nelsontky this feature is awesome.

> URL query params do not update immediately when the http body parameters are updated.

This haven't reported before.

**Pull request merged**
