### PR TITLE
Subfolder functionality

### PR DESCRIPTION
**Pull request by farhan-tariq**
@liyasthomas  Please review this PR. Let me know of any changes required.
I am raising this as a draft PR atm. 
Changes:
- Parsing postman collection - Import/Replace JSON
- Add/Delete/Edit Folder
- Add/Delete/Edit Request
- Add/Delete/Edit Sub-folders
- Move requests between folders by dragging and dropping 
- Editing a request only lets change it's name

WIP
- Working on the functionality of "Save a Request As"

### CODE REVIEW

**Comment by liyasthomas** [comment]
@farhan-tariq this is gold. Only issue I found was drag and drop from one collection's folder to another collection's folder - deletes the request. Everything else is working perfectly, I guess.

Let me know if you need any help.

**Comment by farhan-tariq** [comment]
> @farhan-tariq this is gold. Only issue I found was drag and drop from one collection's folder to another collection's folder - deletes the request. Everything else is working perfectly, I guess.
> 
> Let me know if you need any help.

Yeah it currently only works for moving request between the same collection folders.  Will try adding that at some point.

**Comment by farhan-tariq** [comment]
@liyasthomas I have changed the folder selection to autocomplete search in "Save Request As". Please review this PR and let me know if any changes required.

**Review by liyasthomas — APPROVED** [review]
LGTM. @farhan-tariq thanks for this whole new set of features.

**Comment by farhan-tariq** [comment]
> LGTM. @farhan-tariq thanks for this whole new set of features.

Please merge when possible.

**Comment by liyasthomas** [comment]
Dont close the PR. Closed by accident?

**Review by liyasthomas — APPROVED** [review]

**Comment by farhan-tariq** [comment]
> Dont close the PR. Closed by accident?

Yeah by mistake :D

**Comment by liyasthomas** [comment]
@farhan-tariq I just found this weird issue when signed in - **cannot create folder when signed in**. but works when signed out.
both on https://hoppscotch.io and https://localhost:3000

**Comment by farhan-tariq** [comment]
> @farhan-tariq I just found this weird issue when signed in - **cannot create folder when signed in**. but works when signed out.
> both on https://hoppscotch.io and https://localhost:3000

@liyasthomas I see this on https://hoppscotch.io after signing in with Github account

`Uncaught TypeError: Cannot read property 'team' of undefined
    at Array.<anonymous> (bf49340.js:1)
    at next (0fd9385.js:formatted:25668)
    at 0fd9385.js:formatted:23168`

Not able to log-in with either Google or Github on Local

**Comment by liyasthomas** [comment]
Let me check

**Comment by farhan-tariq** [comment]
I think that was an existing issue

**Comment by liyasthomas** [comment]
I've fixed Teams error. Pull latest `master` and can you now verify the error is gone.

**Comment by farhan-tariq** [comment]
On https://hoppscotch.io there is no error but I am not able to add folders
On Local I get this, I guess due to API restriction

`Uncaught 
t {code: "auth/internal-error", message: "{"error":{"code":403,"message":"Requests from refe…son":"forbidden"}],"status":"PERMISSION_DENIED"}}", a: null}
a: null
code: "auth/internal-error"
message: "{"error":{"code":403,"message":"Requests from referer http://172.22.0.2:3000/ are blocked.","errors":[{"message":"Requests from referer http://172.22.0.2:3000/ are blocked.","domain":"global","reason":"forbidden"}],"status":"PERMISSION_DENIED"}}"
__proto__: Error`

**Comment by liyasthomas** [comment]
Only bug is **cannot create folder when signed in**

**PERMISSION_DENIED** is due to security issue.

**Comment by farhan-tariq** [comment]
@liyasthomas The add folder bug still exists I guess when logged in ?

**Comment by liyasthomas** [comment]
Issue exists, I've asked for help from friend.

**Comment by AndrewBastin** [comment]
> Issue exists, I've asked for help from friend.

Umm, I am the friend :rofl: 

The current store system (well, our implementation) is pretty garbage. I am planning a complete overhaul in that department after Teams support is done.

Here is the fork: Issue exists, I've asked for help from friend.

But for now, I have implemented a fix for the adding folders bug in my fork, check it out.

Here is the fork: https://github.com/AndrewBastin/hoppscotch/tree/fix/folder-no-appear

**Comment by liyasthomas** [comment]
*@AndrewBastin finding bug:*



*coming with fix:*

**Comment by farhan-tariq** [comment]
@AndrewBastin  Your changes LGTM. Looking forward to the complete overhaul of the store system in the future.

**Comment by farhan-tariq** [comment]
@AndrewBastin  Adding a folder to a sub folder does not work anymore. It just adds the newly added sub folder to the main collection instead.

**Pull request merged**
