### PR TITLE
fix: don't cut off the part that's already been typed

### PR DESCRIPTION
**Pull request by liyasthomas**
HFE-47

### Description
The auto-complete component used to cut off the part that's already been typed. This PR fixes that UX and keeps the characters that are already typed.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Review by anwarulislam — APPROVED** [review]
LGTM 💯

**Review by JoelJacobStephen — CHANGES_REQUESTED** [review]
I tried to see if its working in the admin dashboard but it still cuts the part that has already been typed.

**Comment by anwarulislam** [comment]
> I tried to see if its working in the admin dashboard but it still cuts the part that has already been typed.

@JoelJacobStephen you have to run `pnpm i`. I assume you didn't get the latest build from `hoppscotch-ui`. It should work. Just run `pnpm i` in the root directory.

**Review by JoelJacobStephen — APPROVED** [review]
LGTM

**Pull request merged**
