### PR TITLE
feat: socketio bearer authentication

### PR DESCRIPTION
**Pull request by rakshit087**
Working on #1953

### CODE REVIEW

**Comment by rakshit087** [comment]
Worked on the frontend part.  

image

I am kind of confused how to send data to '@hoppscotch/data', since REST authentication uses it to load data. Any help is appreciated.

**Comment by Nijinsha** [comment]
@rakshit087  I think you should be using the token on socketio.vue file.

**Comment by rakshit087** [comment]
Yes I will, caught up in my Final Exams for now. If you want you can take issue from here, fork the fork I made :))

**Comment by rakshit087** [comment]
I have completed most of the work,  

**Without the token**
image  

**With Token**
image  

**With wrong token**
image

**The changes were made according the documentation by SocketIO** 
https://socket.io/docs/v4/middlewares/

The server code is here
```
io.use((socket, next) => {
  const token = socket.handshake.auth.token;
  console.log(token);
  if(checkJWT(token)) next();
  else next(new Error("not authorized"));
})
```

**Review by liyasthomas — APPROVED** [review]

**Comment by rakshit087** [comment]
Thank you for merge!

**Pull request merged**
