### PR TITLE
fix: added Untitled Request to en.json

### LINKED ISSUE #2075: [bug]: Untranslated string
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

The string "Untitled request" is not marked as translatable. It appears [6 places](https://github.com/hoppscotch/hoppscotch/search?q=%22Untitled+request%22) in the source code.

### Steps to reproduce

On the GUI, click the "Save" button. The default name of the new request is "Untitled request". No matter which language is set as interface language.

### Environment

Production

### Version

Cloud

### PR DESCRIPTION
**Pull request by rakshit087**
Closes #2075 

### Description
Added Untitled Request to translations 

- [x] Added to en.json
- [ ] Replace 'Untitled Request' in all files with the translation.

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### Additional Information
This is draft PR, please let me know, where to actually add 'Untitled Request', currently it's under 'error'

### CODE REVIEW

**Comment by liyasthomas** [comment]
This is not the correct approach to add `Untitle request` to translation strings. Hence closing.

We'll be working on this feature very soon.

**Comment by rakshit087** [comment]
Would you please let me know the correct way to do so? Or if there is any
documentation I can refer to.
Would love to contribute.

**Comment by liyasthomas** [comment]
cc: @AndrewBastin

**Comment by liyasthomas** [comment]
This PR has gone stale, hence closing. We're working on another viable solution. Stay tuned for future updates.

**Pull request closed without merging**
