### PR TITLE
feat(filename): added filename in download functional

### LINKED ISSUE #4265: [feature]: Pre-fill file name and extension when downloading a file.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi team,

image

When downloading files, the API client currently doesn't pre-fill the name and extension type of the file.

It would greatly improve my user experience if there would be a "send + download" button which would send the payload and download the response immediately with the name and extension of the file pre-filled.

Optionally you could have a look at how other API clients do this.

### Why should this be worked on?

Basically user experience:

The flow is currently: click send, wait for response, click download, change name, change filetype, save file. 😤

While it could be: click send + download, wait for response, and save file. 😌

### PR DESCRIPTION
**Pull request by shipko**
Closes #4265

### What's changed
Added name for file in all useDownloadResponse methods
- [ ] Not Completed
- [x] Completed

### Notes to reviewers
Maybe we need to move file name in locale files?

### CODE REVIEW

**Review by nivedin — CHANGES_REQUESTED** [review]
we might need to add the file names in locale

**Comment by shipko** [comment]
@nivedin what do you think. 
Why we need to have an availability to download curl command as file that we importing to request? 

Maybe we remove "Download file" button from packages/hoppscotch-common/src/components/http/ImportCurl.vue?

**Comment by nivedin** [comment]
> @nivedin what do you think. Why we need to have an availability to download curl command as file that we importing to request?
> 
> Maybe we remove "Download file" button from packages/hoppscotch-common/src/components/http/ImportCurl.vue?

Good catch, we can remove that @shipko

**Comment by shipko** [comment]
@nivedin PR is done

**Review by nivedin — APPROVED** [review]
LGTM 💯

**Pull request merged**
