### PR TITLE
Sub-Folder Functionality

### PR DESCRIPTION
**Pull request by farhan-tariq**
Hi, I have added the sub-folder functionality for postman collections. 
Please have a look at the PR and let me know if there are any issues.

The image below shows the collection structure.
image

The JSON used to form the folder structure is below:

`{
	"info": {
		"_postman_id": "70f9c0c6-283e-43d2-9ee4-9e31bff55cc8",
		"name": "My Collection",
		"description": "Testing",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Folder",
			"item": [
				{
					"name": "Sub-Folder",
					"item": [
						{
							"name": "Sub-Sub Folder",
							"item": [
								{
									"name": "Request",
									"request": {
										"method": "GET",
										"header": [],
										"url": {
											"raw": "https://httpbin1.org"
										}
									},
									"response": []
								}
							],
							"protocolProfileBehavior": {},
							"_postman_isSubFolder": true
						},
						{
							"name": "My Sub Request",
							"request": {
								"method": "GET",
								"header": [],
								"url": {
									"raw": "https://httpbin2.org"
								}
							},
							"response": []
						}
					],
					"description": "asdasd",
					"protocolProfileBehavior": {},
					"_postman_isSubFolder": true
				},
				{
					"name": "Folder Request",
					"request": {
						"method": "GET",
						"header": [],
						"url": {
							"raw": "https://httpbin3.org"
						},
						"description": "asd"
					},
					"response": []
				}
			],
			"description": "Folder",
			"protocolProfileBehavior": {}
		},
		{
			"name": "Collection Request",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "https://httpbin4.org"
				},
				"description": "Lets see"
			},
			"response": []
		}
	],
	"protocolProfileBehavior": {}
}`

### CODE REVIEW

**Comment by farhan-tariq** [comment]
Perfect @TravisBuddy . Cheers

**Comment by liyasthomas** [comment]
@farhan-sykes thanks for the quick PR. The import/export functionalities are working fine.
Can you check these cases too:

- [] Edit folder name
- [] Edit sub-folder name
- [] Edit request in folder
- [] Edit request in sub-folder

Also it would be great if you could cover these cases too:

- [] Add sub-folders

**Comment by farhan-tariq** [comment]
@liyasthomas  would be happy to. Thanks for pointing that out.

**Comment by liyasthomas** [comment]
Let me know if you need any help with implementing this feature.

**Comment by farhan-tariq** [comment]
@liyasthomas As the sub-folder is a recursive component, I was wondering how can you save the indexes. If you cannot then another idea I had was to have a PATH string which can be passed down as an event to the parent and then used to find the relevant folder and make updates/insertions. 

Another thing is that VUE wants the updates to be set using Vue.set to maintain reactivity. So not sure how can I achieve that. Since you need to the know all the indexes.

**Pull request closed without merging**
