### PR TITLE
graphql: show enums and interfaces

### PR DESCRIPTION
**Pull request by KoHcoJlb**
Hello!
I've added enums and interfaces to the types tab.
This is how it looks:
firefox_02_07_2021_20_26_31_jFUV
firefox_02_07_2021_20_27_02_xwPY
firefox_02_07_2021_20_27_23_ERbY
Apart from that I've made scalar types not clickable.

### CODE REVIEW

**Comment by AndrewBastin** [comment]
Hah! I actually just started working on this at the moment and you completed it!

Looking forward to review this ASAP!

Thank you sooo much for your contribution! ♥️

**Comment by KoHcoJlb** [comment]
Thanks, glad to help. I'll look at the tests tomorrow.

**Review by AndrewBastin — CHANGES_REQUESTED** [review]
Just marking the code review as changes requested until the test stuff is resolved.

I took a peek at the failing test. It is at `components/graphql/__tests__/type.spec.js` and the errors seem to arise mostly from the new props (`gqlTypes`) not being transferred onto the test instance. The fix could be done just by passing in an empty `gqlTypes` array prop value.

I will try to add test entries myself later, but I would appreciate if you could fill those in! ^_^

**Comment by AndrewBastin** [comment]
Also @liyasthomas, are you okay with the UI/UX part ?

**Comment by liyasthomas** [comment]
UI looks good. I approve this 💯

**Comment by KoHcoJlb** [comment]
Fixed falling tests. @AndrewBastin

**Review by AndrewBastin — APPROVED** [review]

**Pull request merged**
