### PR TITLE
feat: Import Insomnia collection to Hoppscotch

### PR DESCRIPTION
**Pull request by anwarulislam**
Closes # 

### Description

I have added a feature to import the Insomnia collection to Hoppscotch. When a user selects Import from JSON I'm checking that is this collection from Insomnia or not. if it's from insomnia then I'm parsing the JSON and transforming it to Postman collection. The parsing script in helpers/utils directory. And the import is working as regular.

- [x] Completed

### Checks

- [x] My pull request adheres to the code style of this project
- [x] All the tests have passed

### CODE REVIEW

**Comment by anwarulislam** [comment]
@liyasthomas I've PRed this feature. Could you please review this PR? Please let me know if any modification needed.

**Comment by AndrewBastin** [comment]
@anwarulislam I tried importing a Insomnia collection and it created a collection with an empty name. 

image

A better approach will be if all those folders were in the root itself ?

Here is the Insomnia collection I tested with (as a ZIP because Github doesn't allow JSON attachments)
[Insomnia_2021-12-20.zip](https://github.com/hoppscotch/hoppscotch/files/7745456/Insomnia_2021-12-20.zip)

**Comment by anwarulislam** [comment]
@AndrewBastin I'll fix this tonight. And will update this PR. Thanks

**Comment by anwarulislam** [comment]
@AndrewBastin also, did you check that there is an error while importing postman collection. 

If any requests has the hostname as variable then that URL doesn't add up after importing. 

Please check this in production. If you found the error let me know. I'll fix this ASAP

**Comment by AndrewBastin** [comment]
@anwarulislam okay noted. We are working on rewriting the entire Import/Export system as the codebase is really old and to be honest really sucks, we are just waiting for this PR to be merged in so we can start the refactor.

**Comment by anwarulislam** [comment]
@AndrewBastin I've fixed the collection name issue of Insomnia. Now, you can import the collection from Insomnia and you will see the name. If no name found then it will be `Untitled`

**Review by AndrewBastin — APPROVED** [review]
@anwarulislam LGTM!!! 💯

Thank you for your contributions!!! ❤️ 

@liyasthomas anything else ?

**Comment by anwarulislam** [comment]
@AndrewBastin Thanks for the review. No nothing else in this branch. You can merge it if it's good to go :D

**Review by liyasthomas — APPROVED** [review]
LGTM. can merge.

**Pull request merged**
