### PR TITLE
Add the ability to export and import state as a file

### PR DESCRIPTION
**Pull request by Earl-Brown**
In my workplace we use Postman, but we have issues sharing our tests between groups (dev, QA, IT) and automating execution of tests.  (Basically, remembering to save environments and collections, as well as the complexity of importing them makes it unusable without prohibitive expense).

I have simplified this need greatly by adding the concept of "workspaces" so we can easily save and restore the entire state.

I fully expect a number of issues to be found with this implementation, and would love advice and assistance for resolving any such issues.

**Deploy preview:** https://deploy-preview-1534--hoppscotch.netlify.app

### CODE REVIEW

**Comment by AndrewBastin** [comment]
Just. Wow. 😍

Thank you sooooo much for this contribution. We were planning to work on this after a refactor of our state management code but we will bring this in since it is done!

Can't wait to review!!! 🚀🚀🚀

**Comment by liyasthomas** [comment]
@Earl-Brown thanks for bring this up. We'll be reviewing and contributing to this branch and hopefully get a working prototype ready asap.

**Comment by Earl-Brown** [comment]
Thanks, I appreciate it!

In the meantime, I'm continuing to make changes that make it easier to 
use myself.

**Comment by Earl-Brown** [comment]
I've been trying to fix the build issue, but ... I'm in unfamiliar territory.  

I'd really appreciate if someone could help me out.  Maybe a VS Live Share session or something?

**Comment by liyasthomas** [comment]
@Earl-Brown build is failing due to the new package-lock.json version bump from v1 to v2. You can ignore this at least for now. We can have a discussion on the implementation of this feature. Feel free to [contact us](https://github.com/hoppscotch/hoppscotch#contact).

**Pull request closed without merging**
