### PR TITLE
feat : smart tree component

### PR DESCRIPTION
**Pull request by nivedin**
### Description
This PR introduces a new tree component that can be used for any tree structure. In this PR the collection component has been refactored using the new smart tree. Smart Tree is a flexible tree view component that converts the data into a tree structure.
The separate components like Collection, Folders, Requests for MyCollection, and TeamsCollection have been removed and made common UI components.

A basic tree component structure will look like below - 

```js
<SmartTree :adapter="someAdapter">
    <template #content="{ node, toggleChildren, isOpen }">
        <SomeComponent :data="node" :is-open="isOpen" @toggle-children="toggleChildren"/> OR <div>{UI of the node}</div>
    </template>
    <template #emptyNode="{ node }">
         <EmptyContentComponent/>
    </template>
</SmartTree>
```

The tree consists of two components and one  Adapter Interface - 

- `Tree` for displaying all the nodes 
- `TreeBranch` for displaying each tree node.
- `SmartTreeAdapter` represents the adapter properties. 

#### <ins>Tree</ins>

- The main tree component, which has `adapter `as the prop. 

- The tree UI is specified by passing it in the slots.

- Content Template returns - 
     - node - The single node data
     - toggleChildren - Function to fetch the children of the node
     - isOpen - Boolean value if the node is open or not
     
- EmptyNode Template returns - 
     - node - The single node data (can be used to differentiate the empty state)     
     
#### <ins>TreeBranch</ins>

- The branch component , which act as the single node, which accepts `node-item` and `adapter` as the props.

#### <ins>Adapter</ins>
 
The adapter which provides the properties of the adapter  - 

- `getChildren` - Function used to fetch the children of the node
   - Accepts `id` as the prop (id of the node which the children is to fetch)
   
 - The TreeNode has to be the type 
 ```js
 type TreeNode<T> = {
  id: string
  data: T
}
 ```
 - id - Unique id to represent the node
 - data - The data to be represented
   - T - type of the data that can be passed form the adapter
   
 - The childrenNode has to be the type ie the data
  ```js
 type ChildrenResult<T> =
  | {
      status: "loading"
    }
  | {
      status: "loaded"
      data: Array<TreeNode<T>>
    }
 ```
 
 It has two status - 

- loading - The data would be null (used in the team collection, when fetching from the db)

- loaded - The data is fetched and the data is passed to data

   
 The loading UI has been provided to the tree since it will be common to all components. 
   
 
 
 ```js
 class SomeAdapter implements SmartTreeAdapter<TypeOfTheNode> {
      // ref because to make the nodes reactive
       constructor(public data: Ref<Type of the incoming data>) {}
       
       getChildren(id): Ref<ChildrenResult<TypeOfTheNode>> {}
 }
 ````
The adapter is then initialized by passing the data

```js
const someAdapter: SmartTreeAdapter<TypeOfTheNode> = new SomeAdapter (DATA)
```
   

 
### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### Additional Information
The whole collection component has been refactored to setup - TS. The functionality of the collection component has been kept the same.

#### TODO: 
 - [x] Issue with root nodes not loading initially (@AndrewBastin)
 - [x] Fix type errors (@AndrewBastin)

### CODE REVIEW

**Review by liyasthomas — DISMISSED** [review]
LGTM

**Comment by AndrewBastin** [comment]
There are some performance issues that need to be improved (mostly for bigger trees) before this can be merged.

I will look into that. Meanwhile, resetting this back as a draft PR.

**Review by AndrewBastin — DISMISSED** [review]
rest everything looks good to me.

@liyasthomas you can do the final review before this is merged.

**Review by liyasthomas — APPROVED** [review]
LGTM 💯

**Pull request merged**
