### PR TITLE
Feature: GraphQl Environments

### PR DESCRIPTION
**Pull request by raghav0307**
This pull request aims to bring the environment functionality to GraphQl.
- Environment tabs allow the user to create new environments with different variable value pairs.
- Created a pre-request tab alongside the header tab to define environment variables for the current query.
- When the user selects an environment it updates the pre-request script with that environment's variable value pairs.

GraphQL

### CODE REVIEW

**Comment by liyasthomas** [comment]
@raghav0307 I guess you need to rebase to latest `main`  branch for graphql environments feature since this doesn't depend on teams branch.

**Comment by raghav0307** [comment]
@liyasthomas I was working on the main branch only. Those merge conflicts were because of the latest code pushed by Osheen. This PR is independent of Teams and doesn't have any code from there.

**Comment by liyasthomas** [comment]
Ahh, got it. anyways GraphQL history PR was squashed before merge. So you will need to rebase to current `main` to remove those commits.

**Comment by liyasthomas** [comment]
Let me know when this is ready for review.

**Pull request closed without merging**
