### PR TITLE
feat: add client credentials

### PR DESCRIPTION
**Pull request by sgtremblay**
Closes https://github.com/hoppscotch/hoppscotch/issues/874 partially, supercedes https://github.com/hoppscotch/hoppscotch/pull/2209 and https://github.com/hoppscotch/hoppscotch/pull/3298

Description
This PR fixes and update this PR https://github.com/hoppscotch/hoppscotch/pull/3298 with updated main.
Adds the option to use the OAuth 2.0 Client Credentials flow.
Adds the option to send Oauth 2.0 Client Credentials in POST body or in Authorization Header.

image

* [ ]  Nicer UI
* [ ]  Show 'Place client credentials in' option only if 'client credentials' is checked
* [ ]  Update docs
* [ ]  Update tests

### Checks
* [x]  My pull request adheres to the code style of this project
* [ ]  My code requires changes to the documentation
* [ ]  I have updated the documentation as required
* [ ]  All the tests have passed

### CODE REVIEW

**Comment by wolfgang-demeter** [comment]
Is there an ETA when this will get merged?

**Comment by Zokiio** [comment]
I am also very interested in this.

**Comment by amddsc** [comment]
+1

there are still some merge conflicts and so far no code review done by codeowners.

**Comment by amk-dev** [comment]
Actually we've a revamped oauth interface introduced in #3885, which introduces most commonly used flows, including `Client Credentials`.  this will be released to production in our next major release, which go live before march ends.

You can test that out and give feedback on whether it it solves your pains regarding using oauth flows in hoppscotch. if you have any changes required to make it work for your usecase, feel free to comment. i'm really looking forward to your feedback.  

For now, I'll close this PR in favor of that (#3885)

**Comment by wolfgang-demeter** [comment]
@amk-dev Does #3885 allow sending Oauth 2.0 Client Credentials as POST request?

**Comment by amk-dev** [comment]
> @amk-dev Does #3885 allow sending Oauth 2.0 Client Credentials as POST request?

yes. we make a POST request to the token endpoint with your credentials.

**Pull request closed without merging**
