### PR TITLE
Added Hindi Language Support

### PR DESCRIPTION
**Pull request by DevenRathod2**
**Added Hindi ( हिंदी ) Language Support For Developers.**

### CODE REVIEW

**Comment by liyasthomas** [comment]
We maintain a separate branch for `i18n` translation. Rebasing this PR to `i18n` branch.

**Review by liyasthomas — APPROVED** [review]
PR looks good to me.
@DevenRathod2 thanks for this quick PR - expecting many more contributions.

**Comment by DevenRathod2** [comment]
> PR looks good to me.
> @DevenRathod2 thanks for this quick PR - expecting many more contributions.

@liyasthomas Thank You For Approval. More to Come 👍

**Comment by DevenRathod2** [comment]
> We maintain a separate branch for `i18n` translation. Rebasing this PR to `i18n` branch.

Ok Got it...

**Pull request merged**
