### PR TITLE
fix: docker node-gyp python not found

### PR DESCRIPTION
**Pull request by lokesh1729**
Docker alpine images generally do not come with python dependencies.
We need to add manually because python is required by node-gyp.

Ref - https://github.com/nodejs/docker-node/issues/282

https://github.com/nodejs/node-gyp#on-unix

### CODE REVIEW

**Comment by liyasthomas** [comment]
Hi @lokesh1729, let me know why you need `Python` and `node-gyp` in Hoppscotch's Docker image?

**Comment by lokesh1729** [comment]
@liyasthomas - I think it requires because node-gyp needs it. Please refer - https://github.com/nodejs/node-gyp#on-unix and we need node-gyp to compile node addons. I am using mac M1 and I got the error saying node-gyp cannot find python.

**Comment by liyasthomas** [comment]
Can you produce the logs?
I too have a Mac M1 and had no error with the current image.

**Comment by liyasthomas** [comment]
Feel free to reopen the PR if necessary.

**Comment by lokesh1729** [comment]
@liyasthomas Hi, here's the error stack trace

```
~/projects/hoppscotch (main ✔) ᐅ docker-compose build
[+] Building 24.0s (11/13)
 => [internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 32B                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                            0.0s
 => => transferring context: 35B                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/node:lts-alpine                                                                                                           1.2s
 => [1/9] FROM docker.io/library/node:lts-alpine@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b                                                     0.0s
 => [internal] load build context                                                                                                                                            0.1s
 => => transferring context: 53.30kB                                                                                                                                         0.1s
 => CACHED [2/9] RUN apk add --update --no-cache   git                                                                                                                       0.0s
 => CACHED [3/9] WORKDIR /app                                                                                                                                                0.0s
 => CACHED [4/9] ADD . /app/                                                                                                                                                 0.0s
 => CACHED [5/9] COPY . .                                                                                                                                                    0.0s
 => CACHED [6/9] RUN npm install -g pnpm                                                                                                                                     0.0s
 => ERROR [7/9] RUN pnpm i --unsafe-perm=true                                                                                                                               22.6s
------
 > [7/9] RUN pnpm i --unsafe-perm=true:
#11 0.403 Scope: all 4 workspace projects
#11 0.502 Lockfile is up-to-date, resolution step is skipped
#11 0.587 Progress: resolved 1, reused 0, downloaded 0, added 0
#11 0.863 Packages: +2189
#11 0.863 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#11 1.286 Packages are hard linked from the content-addressable store to the virtual store.
#11 1.286   Content-addressable store is at: /root/.pnpm-store/v3
#11 1.286   Virtual store is at:             node_modules/.pnpm
#11 1.601 Progress: resolved 2189, reused 0, downloaded 61, added 53
#11 2.609 Progress: resolved 2189, reused 0, downloaded 221, added 215
#11 3.610 Progress: resolved 2189, reused 0, downloaded 312, added 310
#11 4.609 Progress: resolved 2189, reused 0, downloaded 411, added 409
#11 5.610 Progress: resolved 2189, reused 0, downloaded 610, added 600
#11 6.610 Progress: resolved 2189, reused 0, downloaded 726, added 726
#11 7.646 Progress: resolved 2189, reused 0, downloaded 767, added 765
#11 8.649 Progress: resolved 2189, reused 0, downloaded 877, added 877
#11 9.651 Progress: resolved 2189, reused 0, downloaded 931, added 931
#11 10.65 Progress: resolved 2189, reused 0, downloaded 1142, added 1138
#11 11.65 Progress: resolved 2189, reused 0, downloaded 1468, added 1468
#11 12.67 Progress: resolved 2189, reused 0, downloaded 1571, added 1569
#11 13.67 Progress: resolved 2189, reused 0, downloaded 1671, added 1668
#11 14.67 Progress: resolved 2189, reused 0, downloaded 1781, added 1781
#11 15.68 Progress: resolved 2189, reused 0, downloaded 1816, added 1816
#11 16.68 Progress: resolved 2189, reused 0, downloaded 1906, added 1906
#11 17.68 Progress: resolved 2189, reused 0, downloaded 1954, added 1954
#11 18.68 Progress: resolved 2189, reused 0, downloaded 2072, added 2072
#11 19.68 Progress: resolved 2189, reused 0, downloaded 2123, added 2123
#11 20.68 Progress: resolved 2189, reused 0, downloaded 2186, added 2186
#11 21.68 Progress: resolved 2189, reused 0, downloaded 2189, added 2189, done
#11 21.97 .../deasync@0.1.23/node_modules/deasync install$ node ./build.js
#11 21.97 .../node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
#11 21.97 .../core-js@3.6.5/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
#11 21.97 .../core-js@3.19.1/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
#11 21.97 .../core-js@2.6.12/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
#11 22.06 .../core-js@3.19.1/node_modules/core-js postinstall: Done
#11 22.06 .../esbuild@0.12.29/node_modules/esbuild postinstall$ node install.js
#11 22.07 .../node_modules/core-js-pure postinstall: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
#11 22.07 .../node_modules/core-js-pure postinstall: The project needs your help! Please consider supporting of core-js:
#11 22.07 .../node_modules/core-js-pure postinstall: > https://opencollective.com/core-js
#11 22.07 .../node_modules/core-js-pure postinstall: > https://patreon.com/zloirock
#11 22.07 .../node_modules/core-js-pure postinstall: > https://paypal.me/zloirock
#11 22.07 .../node_modules/core-js-pure postinstall: > bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz
#11 22.07 .../node_modules/core-js-pure postinstall: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
#11 22.08 .../node_modules/core-js-pure postinstall: Done
#11 22.09 .../core-js@3.6.5/node_modules/core-js postinstall: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
#11 22.09 .../core-js@3.6.5/node_modules/core-js postinstall: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
#11 22.09 .../core-js@3.6.5/node_modules/core-js postinstall: > https://opencollective.com/core-js
#11 22.09 .../core-js@3.6.5/node_modules/core-js postinstall: > https://www.patreon.com/zloirock
#11 22.09 .../core-js@3.6.5/node_modules/core-js postinstall: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
#11 22.10 .../node_modules/protobufjs postinstall$ node scripts/postinstall
#11 22.11 .../core-js@2.6.12/node_modules/core-js postinstall: Done
#11 22.11 .../core-js@3.6.5/node_modules/core-js postinstall: Done
#11 22.13 .../deasync@0.1.23/node_modules/deasync install: gyp info it worked if it ends with ok
#11 22.13 .../deasync@0.1.23/node_modules/deasync install: gyp info using node-gyp@8.4.1
#11 22.13 .../deasync@0.1.23/node_modules/deasync install: gyp info using node@16.13.0 | linux | arm64
#11 22.15 .../node_modules/protobufjs postinstall: Done
#11 22.17 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python Python is not set from command line or npm configuration
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python Python is not set from environment variable PYTHON
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python checking if "python3" can be used
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python - "python3" is not in PATH or produced an error
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python checking if "python" can be used
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python - "python" is not in PATH or produced an error
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python **********************************************************
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python You need to install the latest version of Python.
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python you can try one of the following options:
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python   (accepted by both node-gyp and npm)
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python - Set the environment variable PYTHON
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python - Set the npm configuration variable python:
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python For more information consult the documentation at:
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python **********************************************************
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! find Python
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! configure error
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! stack Error: Could not find any Python installation to use
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:330:47)
#11 22.18 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:159:21)
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:202:16)
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:294:16)
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! stack     at exithandler (node:child_process:404:5)
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:416:5)
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! stack     at onErrorNT (node:internal/child_process:477:16)
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! System Linux 5.10.47-linuxkit
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! cwd /app/node_modules/.pnpm/deasync@0.1.23/node_modules/deasync
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! node -v v16.13.0
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! node-gyp -v v8.4.1
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: gyp ERR! not ok
#11 22.19 .../deasync@0.1.23/node_modules/deasync install: Build failed
#11 22.20 .../deasync@0.1.23/node_modules/deasync install: Failed
#11 22.20  ELIFECYCLE  Command failed with exit code 1.
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c pnpm i --unsafe-perm=true]: exit code: 1
```

**Comment by lokesh1729** [comment]
@liyasthomas I'm not able to re-open the PR. Can you take a look at the above error trace ?

**Comment by lokesh1729** [comment]
@liyasthomas As much as I know, `node-gyp` is required to build node.js and its add-on modules. In this case, we are using alpine which is a very lightweight image. It doesn't have python installed. But python is required to install addon modules.

**Review by liyasthomas — DISMISSED** [review]
LGTM. Thank you for the quick PR and the clarification.

**Review by liyasthomas — APPROVED** [review]

**Comment by InclinedScorpio** [comment]
@liyasthomas  - Hi Thomas !
It's been 4th day now and I am still struggling to install "sqlite3" in node 14 docker alpine image.
I would really appreciate it if you can show me how to create the **Dockerfile** for this as I keep getting python errors.
I have tried multiple things but nothing worked.

**Comment by AndrewBastin** [comment]
@InclinedScorpio Why are you trying to install sqlite3 on our Docker image ?

Please provide steps to reproduce or error logs.

**Comment by InclinedScorpio** [comment]
Hi @AndrewBastin 

On a Node(Version 14) Docker Image, I am trying to install sqlite3 as the node application depends upon sqlite3.
I am trying to install sqlite3 using npm but unable to do so since a long time.
Any help will be appreciated.

**Comment by AndrewBastin** [comment]
```
On a Node(Version 14) Docker Image, I am trying to install sqlite3 as the node application depends upon sqlite3.
```

@InclinedScorpio which Node application ?

Can you provide build logs ?

**Comment by InclinedScorpio** [comment]
@AndrewBastin, I am actually using it in my company's laptop so can't share the exact logs.

The error which I can see is, it's trying to access some amazon URL while installation but due to company proxy it's not able to contact and apparently returning 403. 

Is there by any means I can do some alternative to prevent this behavior or use some other similar package?

**Comment by AndrewBastin** [comment]
@InclinedScorpio so you are trying to build the Hoppscotch docker image in your PC behind a proxy ?


Well, we won't be doing anything as of right now to build within the proxy. If this is an issue you think would require a fix from our end, please open it up as an issue and not further bring up the conversation in this thread.

**Comment by InclinedScorpio** [comment]
I am trying to use the sqlite3 package in a node image, I am not using Hoppscotch.

Anyways as this conversation is not related to the thread I won't take it forward.
Thanks, @AndrewBastin for the reply!

**Comment by AndrewBastin** [comment]
@InclinedScorpio Dude. Seriously.

This is the Hoppscotch project repo. Please don't bring in non-applicable issues to this repo. Only Hoppscotch issues are welcome here.

Please open up an issue on the relevant channels or open a question in StackOverflow to get your answer.

**Pull request merged**
