### PR TITLE
chore(i18n): update tw translations

### PR DESCRIPTION
**Pull request by SiderealArt**

### CODE REVIEW

**Review by liyasthomas — APPROVED** [review]
Hi @SiderealArt, thanks for taking the time to help us translate Hoppscotch to your favorite languages.

LTGM.

**Comment by TonyRL** [comment]
Just curious.
Haven't I provided most of the tw translations similar to  this PR from prior PR https://github.com/hoppscotch/hoppscotch/pull/1948 already?

e.g.,
line 140 `Connect to a GraphQL...`
line 145 `Invite list is empty`
line 149 ...
approximately line 265 translations for the whole profile, etc... and so on.

**Comment by TonyRL** [comment]
It seems @SiderealArt started working from `main` branch and opened this PR trying to merge into `main`.

A note should be added to `TRANSLATIONS.md` @liyasthomas telling contributors 
- should checkout `i18n` branch before working on existing translations
- should not start their work from `main` branch for existing translations
- `i18n` will be merged into `main` weekly or so

Otherwise, it is possible that one day a contributor came, saw untranslated strings in `tw.json` or other languages on `main`, didn't checkout `i18n`, did his/her translation works and initiated a PR to `main`. Repo maintainers switched base branch, merged and BOOM.
All those unmerged works in-between `main` and `i18n` disappeared.

---

Side note for @SiderealArt:
From `Owners can add, edit, and delete requests, collections and team members.` to `擁有者能夠新增、編輯、和刪除請求、組合、及團隊成員。`. 
And also from `Editors can add, edit, and delete requests.` to `編輯者能夠新增、編輯、和刪除請求。`

A `、` right before `和` or `及`. Really? That's not how `、` works, right? I don't see [the Ministry of Education's punctuation manual](https://language.moe.gov.tw/001/upload/files/site_content/m0001/hau/h3.htm) or [pedia from Ministry of Education](https://pedia.cloud.edu.tw/Entry/Detail/?title=%E9%A0%93%E8%99%9F) telling you can do that. Or did I miss something in my education?

Second, it would be better to keep the whole translation consistent. All of the translated strings in both `main` and `i18n`'s `tw.json` have translated `you` to `你`. Translating `you` to `您` introduces inconsistency, which has been fixed in https://github.com/hoppscotch/hoppscotch/pull/1944 (See solid bullet point 7)

Apart from that, it would be better to finish off all translations before submitting them. A few strings in `team` left untranslated(which I did translate in #1948).

Having said that, there are a few nice catches like
https://github.com/hoppscotch/hoppscotch/blob/0bcfeb86aefae40d4ea3960b6a199f7df7cc176d/packages/hoppscotch-app/locales/tw.json#L34 https://github.com/hoppscotch/hoppscotch/blob/0bcfeb86aefae40d4ea3960b6a199f7df7cc176d/packages/hoppscotch-app/locales/tw.json#L316 which I didn't notice (plus possibly outdated dict from [OpenCC](https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TWPhrasesIT.txt#L85)).

---

Anyways, would it be possible to revert this PR and cherry-pick back https://github.com/hoppscotch/hoppscotch/pull/1948 or https://github.com/hoppscotch/hoppscotch/commit/bed216b6a911abb930aacf02036495f5bcec9b1e and let @SiderealArt put some good stuff in this PR back?

**Comment by liyasthomas** [comment]
Thanks for pointing out the mistakes in the translations guide. I've updated the guide with proper information on setting the base branch to `i18n`. And also updated the `tw.json` with your translations. Thanks again.

**Comment by SiderealArt** [comment]
@TonyRL 
> A 、 right before 和 or 及. Really? That's not how 、 works, right? I don't see the Ministry of Education's punctuation manual or pedia from Ministry of Education telling you can do that. Or did I miss something in my education?

The last 、should be ，, e.g., `編輯者能夠新增、編輯、和刪除請求。` →`編輯者能夠新增、編輯，和刪除請求。`. It's my fault.

> Second, it would be better to keep the whole translation consistent. All of the translated strings in both main and i18n's tw.json have translated you to 你. Translating you to 您 introduces inconsistency, which has been fixed in #1944 (See solid bullet point 7)

Since my changes were all reverted and I'll need to submit another PR, I think we can take the opportunity to change all the 你 into 您。 What's your opinion?

**Comment by TonyRL** [comment]
> @TonyRL
> 
> > A 、 right before 和 or 及. Really? That's not how 、 works, right? I don't see the Ministry of Education's punctuation manual or pedia from Ministry of Education telling you can do that. Or did I miss something in my education?
> 
> The last 、should be ，, e.g., `編輯者能夠新增、編輯、和刪除請求。` →`編輯者能夠新增、編輯，和刪除請求。`. It's my fault.
> 
> > Second, it would be better to keep the whole translation consistent. All of the translated strings in both main and i18n's tw.json have translated you to 你. Translating you to 您 introduces inconsistency, which has been fixed in #1944 (See solid bullet point 7)
> 
> Since my changes were all reverted and I'll need to submit another PR, I think we can take the opportunity to change all the 你 into 您。 What's your opinion?

LGTM

**Pull request merged**
