### PR TITLE
i18n: update vi.json

### PR DESCRIPTION
**Pull request by ducconit**
### Description
This pull request aims to improve the Vietnamese language translations for better accuracy and meaningfulness. The changes made in this pull request include refining the wording and ensuring the translations align with the intended context. The goal is to enhance the user experience and provide more reliable and understandable translations in Vietnamese.

### CODE REVIEW

**Comment by ducconit** [comment]
Hi team,

I just wanted to clarify that I checked out from the branch "chore-i18n," which already includes changes from other files. In this pull request, I solely focused on modifying the content of the "vi.json" file to improve the Vietnamese language translations. The changes made in this file should not conflict with any other ongoing changes in other files.

Please review the modifications and let me know if any further adjustments are required. Thank you!

**Comment by liyasthomas** [comment]
Hi @ducconit, you took the fork of a diverged branch as the head for your change hence the unintended changes. Since you're raising the PR against the main branch, you should take the main as the head of your working branch as well.

Stash your changes from the current working branch and switch to the main branch to set it as your working branch head. Then pop the stashed changes, commit the changes, and force-push it to your remote branch chore-i18n-vi.

I'll convert this PR to a draft till all merge conflicts are resolved.

**Comment by ducconit** [comment]
> Hi @ducconit, you took the fork of a diverged branch as the head for your change hence the unintended changes. Since you're raising the PR against the main branch, you should take the main as the head of your working branch as well.
> 
> Stash your changes from the current working branch and switch to the main branch to set it as your working branch head. Then pop the stashed changes, commit the changes, and force-push it to your remote branch chore-i18n-vi.
> 
> I'll convert this PR to a draft till all merge conflicts are resolved.

Thank you for pointing out the oversight. I have resolved the conflict and ensured that the changes have been integrated correctly. I have updated the PR to reflect these changes. I look forward to receiving your feedback and further comments.

**Review by liyasthomas — APPROVED** [review]
LGTM 💯

**Pull request merged**
