### PR TITLE
Teams

### LINKED ISSUE #580: Add support for teams
Postman teams for postwoman.

More details in #507 (which is sort of a prequel for this issue)

### PR DESCRIPTION
**Pull request by liyasthomas**
**Tasks**
- [x] UI
- [x] Create team / member
- [x] Edit team / member
- [x] Delete team / member
- [x] Pemissions (read, write)
- [x] Sharing

Demo: https://deploy-preview-879--postwoman.netlify.app

- [x] 1. Sign in with GitHub / Google
- [x] 2. Go to Settings > Teams
- [x] 3. Create team / add members email and permissions.
- [x] 4. Members will be able to access (read, write) collections, environments shared with them.

Resolves #580

### CODE REVIEW

**Comment by zhangzhaohong** [comment]
What time would you merge this MR, so that we can use v2.0 in our team, all of us are waiting for this version yet.

**Comment by faztp12** [comment]
Powerr varatte Powerr Powerr 💪 💪

**Comment by gianlucapisati** [comment]
Hi! Any news on this functionality?

**Comment by liyasthomas** [comment]
We're internally testing beta Teams support. Stay tuned for release.

**Comment by zhangzhaohong** [comment]
Do you have any new progress yet？

**Comment by liyasthomas** [comment]
https://github.com/hoppscotch/hoppscotch/tree/feat/teams-new

**Comment by liyasthomas** [comment]
Hi everyone,

### **Today we're excited to announce that the most awaited "Teams collaboration" feature is now out for [Beta users](https://forms.gle/XPYDMp8m6JHNWcYp9).**

# **[Join Hoppscotch Teams β waiting list now →](https://forms.gle/XPYDMp8m6JHNWcYp9)**

We'll be accepting 100 users per week ❤️ 

Closing this PR on behalf of #1641

**Pull request closed without merging**
