### PR TITLE
Add Salesforce Apex codegen

### PR DESCRIPTION
**Pull request by silentmatt**
Apex wasn't mentioned in #1190 but this would be useful for my job, and I figured other people might want it too.

### CODE REVIEW

**Review by liyasthomas — DISMISSED** [review]
That's a nice addition. Thanks for the PR.

**Comment by liyasthomas** [comment]
@silentmatt can you rebase to latest `master` branch to fix merge conflicts.

**Comment by silentmatt** [comment]
@liyasthomas Done.

**Review by liyasthomas — APPROVED** [review]
LGTM

**Pull request merged**
