### PR TITLE
fix(selfhost-web): perform logout if the silent refresh attempt fails

### LINKED ISSUE #3701: [bug]: Auth cookies are not removal from selfhost-web after expired it
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I log into my account, I wait for the expiration of the refresh_token JWT (specified in the REFRESH_TOKEN_VALIDITY parameter). After that, I log into the selfhost-web component and see that my account is still active, but any GraphQL method  related with account is not working.

I expect that after expiration refresh token I will be logout and my cookie will be removed.

### Steps to reproduce

1. Log in into my account through selfhost-web component
2. Waiting for the expiration of the cookie parameter JWT refresh_token 
3. Open page of the selfhost-web component
4. See that account is still be active.

### Environment

Production

### Version

Self-hosted

### PR DESCRIPTION
**Pull request by shipko**
Closes #3701

### Description
This PR fixes the bug found in refresh token feature

- Fix problem with refreshToken method when backend returns 401 code
- When refreshToken returns false then completing the user session

- [ ] Not Completed
- [x] Completed

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by shipko** [comment]
@balub please review it

**Review by jamesgeorge007 — APPROVED** [review]

**Comment by jamesgeorge007** [comment]
Based on the existing implementation, the silent refresh flow would kick in only when the user performs a page reload and a log-out during the silent refresh flow when the refresh token has expired. We'd want to explore having this during page visits so that any actions performed while the tokens are expired will log them out, preventing exceptions due to unauthorized access.

**Review by jamesgeorge007 — APPROVED** [review]

**Review by balub — APPROVED** [review]
Tested locally LGTM 🚀 .

**Comment by Ashraff-547** [comment]
tested locally LGTM.

**Pull request merged**
