### PR TITLE
refactor: move sentry to platform

### PR DESCRIPTION
**Pull request by nivedin**
Closes HFE-230 HFE-282

### Description
This PR moves the sentry from hoppscotch-common to platform.

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
Updates to empty states were made in #3452.

**Comment by liyasthomas** [comment]
@nivedin revert this commit: https://github.com/hoppscotch/hoppscotch/pull/3451/commits/6dfca8151846e8d01bbcf6e61b99d10d2b3a313e

**Comment by nivedin** [comment]
> @nivedin revert this commit: [6dfca81](https://github.com/hoppscotch/hoppscotch/commit/6dfca8151846e8d01bbcf6e61b99d10d2b3a313e)

reverted this commit

**Comment by jamesgeorge007** [comment]
Shouldn't we target the [release/2023.12.0](https://github.com/hoppscotch/hoppscotch/tree/release/2023.12.0) branch?

**Review by jamesgeorge007 — APPROVED** [review]

**Comment by jamesgeorge007** [comment]
Could you resolve the conflicts?

**Review by AndrewBastin — APPROVED** [review]

**Pull request merged**
