### PR TITLE
refactor: collection search query

### PR DESCRIPTION
**Pull request by balub**
Closes HSB-377

### Description

In this PR we are changing the TeamCollection title search query to a query parameter from a path parameter.
Changed from `/team-collections/search/<teamId>/12345` to `/team-collections/search/<teamId>?searchQuery=12345`.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Review by mirarifhasan — COMMENTED** [review]
Getting an error in team-collection.service.ts
(1166 line)

Screenshot 2024-03-19 at 4 22 51 PM

**Comment by balub** [comment]
@mirarifhasan can you tell me what the search query was that resulted in this error?

**Comment by mirarifhasan** [comment]
> @mirarifhasan can you tell me what the search query was that resulted in this error?

@balub  `ClickUp`

**Comment by balub** [comment]
@mirarifhasan Can you confirm if the migration was run properly?

**Review by mirarifhasan — APPROVED** [review]

**Comment by balub** [comment]
@mirarifhasan was the issue resolved, if it was what was the issue?

**Comment by mirarifhasan** [comment]
> @mirarifhasan was the issue resolved, if it was what was the issue?

There was a migration related issues in my end. After running a migration it resolves.

**Pull request merged**
