### PR TITLE
bug: convert to UTC time before using toISO().

### LINKED ISSUE #3577: Magic Link Toen expired immediately with non-default timezone
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

login with email, the token is expired immediately. 

### Steps to reproduce

I am deploying with kubernetes and mounted a timezone file like this:
```
volumeMounts:     
- name: tz
  mountPath: /etc/localtime
volumes:
- name: tz
  hostPath:
  path: /usr/share/zoneinfo/Asia/Shanghai
```

I am doing this is because I am in UTC+8, to see correct time such as in logs.

but this will fail the email magic link login 

### Environment

Production

### Version

Self-hosted

### PR DESCRIPTION
**Pull request by Voimulax**
Closes #3577

### Description

Convert to UTC time before using toISO().

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### Additional Information

Nothing.

### CODE REVIEW

**Review by balub — APPROVED** [review]

**Comment by balub** [comment]
@Voimulax Please rebase your branch against the lasted commits in `main`.

**Review by mirarifhasan — APPROVED** [review]
LGTM, tested locally.

**Comment by liyasthomas** [comment]
@balub @mirarifhasan if this closes #3577, sort out this PR and bring this change.

**Comment by reubenjs** [comment]
I also had this issue and voimulax' pr fixes it for me. Will it be merged?

**Pull request closed without merging**
