### PR TITLE
[wip] switching from material icon-font to svg

### LINKED ISSUE #1025: [website] use svg instead of font-icons
not sure if that's a a bug report or a feature request, but it is existing and has negative impact, so its a bug.

postwoman font-icons

not many places still use this technology, and for a good reason

### PR DESCRIPTION
**Pull request by dym-sh**
progress:

1. added `<icon icon="some_icon_id">` component
2. replaced all `<i>`s  with `<icon>`
3. added ~~all~~ used material icons in svg (including some missing in official github repo, and only available on md-website)
4. converted inlined svg into svg files (except for logo)
5. [currently] figuring out why `<icon>` component not rendering lmao

This PR fixes #1025

### CODE REVIEW

**Comment by liyasthomas** [comment]
@dym-sh 
Oops, I think you included all svg icons from material icon set. Better to add only the icons we use. I'm sure it'll be maximum of 12-15 icons.

**Comment by dym-sh** [comment]
icons used – 92: access_time, account_circle, add, arrow_drop_down, arrow_right, assignment_returned, assistant, attach_file, brush, chrome, clear, clear_all, close, cloud, cloud_download, cloud_upload, code, content_copy, create, create_new_folder, delete, done, donut_large, drag_indicator, edit, email, error_outline, exit_to_app, expand_less, expand_more, extension, extensions, favorite, firefox, first_page, folder, folder_open, folder_shared, folder_special, github, google, graphql, help_outline, history, http, import_export, input, insert_drive_file, keyboard, language, last_page, library_add, local_parking, login, more_vert, note, offline_bolt, open_in_new, payment, person, photo_filter, play_arrow, post_add, public, restore, save_alt, schedule, search, send, settings, share, sort, sort_by_alpha, star, star_border, style, sync, sync_disabled, tab, testReport, timeline, timer, toc, topic, translate, twitter, unfold_less, unfold_more, visibility, visibility_off, vpn_key, watch_later

**Comment by liyasthomas** [comment]
@dym-sh did you pushed the all icons folder?

**Comment by AndrewBastin** [comment]
Converting this into a draft PR since it's not done yet.

**Comment by AndrewBastin** [comment]
@dym-sh how is the progress ?

**Comment by dym-sh** [comment]
i mean, if you could just say why this is not rendering: https://github.com/dym-sh/postwoman/blob/master/components/ui/icon.vue

it would be done already

**Comment by liyasthomas** [comment]
@dym-sh refer this PR #1091 as starting point.

**Pull request closed without merging**
