### PR TITLE
feat: parse query parameters

### PR DESCRIPTION
**Pull request by levz0r**
### Description

This PR adds a small, yet convenient UX improvement that is similar to Postman's behavior: when pasting and/or modifying the request URL, the query parameters will be parsed and modified accordingly in the query parameters section.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by AndrewBastin** [comment]
We had thought about this sort of an implementation before but we decided against as we thought of the URL entry as something more static and fixed instead of being a dynamic sort of a thing like how we envision the parameters section as.

For example, if I enter in `?name=andrew`, the fields do get populated but it removes existing params added.

Hoppscotch doesn't consider the Parameter section as a reflection of the URL bar unlike what Postman does, we consider them as separate things, one meant to be more static, other meant to be more dynamic.

If we are to consider moving ahead with this implementation, I would prefer just having a Computed Params sorta subsection  (similar to Computed Headers (try using authentication or POST body and look at the headers section)) where the URL entries are also shown.

Not in terms of this PR, but in general: we are not looking forward to building an open-source Postman here, most of our users switch from Postman hating its direction, it doesn't make sense we just add their stuff without scrutiny.

**Comment by levz0r** [comment]
@AndrewBastin thank you for the detailed response. 
I share Your opinion about Postman, but I think this particular feature of Postman is useful.
What if this feature would be added under experiments and its usage would be measured before migrating into core functionality?

**Comment by AndrewBastin** [comment]
@levz0r what about a middle ground to this as I mentioned in my comment.

We see the URL part of the request a bit differently in the sense that we expect it to not change a lot and be minimal. You can introduce parameters there, but usually the norm is to put things which are static there. You can think it more like an 'endpoint' field.

So, what I propose is a more middle approach like what we have for headers:
image

We internally call it Computed Headers, where these headers are applied due to some indirect side effect (in this example, it is because I set Body type to Form Data and added Basic Auth). We can introduce something similar for Parameters and maybe even allow for additional features around like moving parameters from URL to Params and back.

Because, the implementation you are proposing is basically against how Hoppscotch used to work from the beginning, so introducing this change will either cause inconsistencies (based on this experiement being enabled or not) and many other edge cases your implementation in this PR isn't currently handling.

**Comment by AndrewBastin** [comment]
Closing PR due to inactivity.

**Pull request closed without merging**
