### PR TITLE
Integrate Uffizzi PR Environments

### PR DESCRIPTION
**Pull request by waveywaves**
### Description

- [x] Add Github Workflow for uffizzi PR environments
- [x] Add docker compose template compatible with uffizzi PR envs

### Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### Additional Information

I want to invite the maintainers of Hoppscotch to the Uffizzi project created for them. The PR setups up PR Environments for Hoppscotch to ease development and reviews. Reviewers should be able to see a preview of the PR as a hosted service. The URL of the service will be provided in a comment on the PR itself. I want to invite the maintainers of Hoppscotch to the uffizzi project to get an idea of what the platform looks like. Uffizzi is free for Hoppscotch.

### CODE REVIEW

**Comment by waveywaves** [comment]
For this initially I would require the mail address of the developers of NocoDB to invite to the project.
cc @AndrewBastin @liyasthomas

**Comment by waveywaves** [comment]
For this initially I would require the mail address of the developers of Hoppscotch to invite to the project.
cc @AndrewBastin @liyasthomas

**Comment by waveywaves** [comment]
This is my working fork for this PR https://github.com/waveywaves/hoppscotch/pull/3 
you can see that the PR has been built and then deployed to https://deployment-5293-hoppscotch-46my.app.uffizzi.com/

**Comment by liyasthomas** [comment]
We're not considering Uffizzi for test deployments. Hence closing this PR.

**Pull request closed without merging**
