### PR TITLE
Malayalam

### PR DESCRIPTION
**Pull request by vachan-maker**
Please check the translation before merging.

### CODE REVIEW

**Review by liyasthomas — APPROVED** [review]
I love this. It would be great if you could translate remaining strings too.

**Comment by vachan-maker** [comment]
> 
> 
> I love this. It would be great if you could translate remaining strings too.

I will finish it when I get time. I only have limited knowledge in programming and github. So I don't know how to add a commit to this PR. Anyway, I will finish this.

**Comment by liyasthomas** [comment]
@vachan-maker I can help you. Actually it's quite easy. You can connect with me via [Telegram](https://t.me/liyasthomas) and I'll give you instructions in _Malayalam_ itself.

**Comment by vachan-maker** [comment]
> 
> 
> @vachan-maker I can help you. Actually it's quite easy. You just need to push your further commits to the same branch which is `patch-1`. You can connect with me via [Telegram](https://t.me/liyasthomas) and I'll give you instructions in _Malayalam_ itself.

I have sent you a message. Thanks

**Review by liyasthomas — APPROVED** [review]

**Comment by liyasthomas** [comment]
I updated the remaining strings.

**Pull request merged**
