### PR TITLE
duplicate request in collections.

### PR DESCRIPTION
**Pull request by 0xc0Der**
related to issue #1751.

### CODE REVIEW

**Review by AndrewBastin — CHANGES_REQUESTED** [review]
@0xc0Der great work on the PR!

But a small suggestion, while duplicating, isn't some suffix a good thing ?

For example, if I duplicate, "My Request", I don't think getting another request with the same name is nice. Something like "My Request - Duplicate" or something similar will be better.

@liyasthomas input ?

**Comment by liyasthomas** [comment]
I guess renaming the duplicated request to "My request - Duplicate" is good.

**Comment by 0xc0Der** [comment]
noted. working on it.

**Comment by 0xc0Der** [comment]
fixed:
added '-Copy' to request name.

**Review by AndrewBastin — APPROVED** [review]
LGTM 💯 

Thank you for your PR @0xc0Der ! 🤗

**Pull request merged**
