### PR TITLE
fix: Self-host unable to use Azure oauth

### LINKED ISSUE #3050: [bug]: Self-host unable to use Azure oauth
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

With a new setup and everything setup to use Microsoft Auth when I try to login the backend server gets an error, it seems "profile" data is empty

```
[Nest] 180  - 05/10/2023, 2:01:27 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'emails')
TypeError: Cannot read properties of undefined (reading 'emails')
    at MicrosoftStrategy.validate (/usr/src/app/src/auth/strategies/microsoft.strategy.ts:27:15)
    at MicrosoftStrategy.<anonymous> (/usr/src/app/node_modules/.pnpm/@nestjs+passport@9.0.0_@nestjs+common@9.2.1_passport@0.6.0/node_modules/@nestjs/passport/dist/passport/passport.strategy.js:20:55)
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/.pnpm/@nestjs+passport@9.0.0_@nestjs+common@9.2.1_passport@0.6.0/node_modules/@nestjs/passport/dist/passport/passport.strategy.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/node_modules/.pnpm/@nestjs+passport@9.0.0_@nestjs+common@9.2.1_passport@0.6.0/node_modules/@nestjs/passport/dist/passport/passport.strategy.js:4:12)
    at MicrosoftStrategy.callback [as _verify] (/usr/src/app/node_modules/.pnpm/@nestjs+passport@9.0.0_@nestjs+common@9.2.1_passport@0.6.0/node_modules/@nestjs/passport/dist/passport/passport.strategy.js:17:45)
    at /usr/src/app/node_modules/.pnpm/passport-oauth2@1.6.1/node_modules/passport-oauth2/lib/strategy.js:198:24
    at /usr/src/app/node_modules/.pnpm/passport-microsoft@1.0.0/node_modules/passport-microsoft/lib/strategy.js:117:17
    at passBackControl (/usr/src/app/node_modules/.pnpm/oauth@0.9.15/node_modules/oauth/lib/oauth2.js:134:9)
```

After some debugging i've found the problem and editing the file: `/packages/hoppscotch-backend/src/auth/strategies/microsoft.strategy.ts` and adding a dummie param to this funcion like this: `  async validate(accessToken: string, refreshToken: string, dummie, profile, done) {`
Solves the null problem and the function can access to profile data.

But then it seems prisma gets in to a loop creating the user to the database with this error.

```
[Nest] 180  - 05/11/2023, 6:10:48 AM   ERROR [ExceptionsHandler] Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at BufferList.hasOwnProperty (<anonymous>)
    at getDepth (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:33225:42)
    at getDepth (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:33229:21)
    at getDepth (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:33229:21)
    at getDepth (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:33229:21)
    at getDepth (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:33229:21)
    at getDepth (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:33229:21)
    at getDepth (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:33229:21)
    at getDepth (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:33229:21)
    at getDepth (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:33229:21)
```

I'm not expert enought to solve this problem by my self and send a PR, sorry...

### Steps to reproduce

1. Create a new self-hostes hoppscotch
2. Add azure oauth config
3. Try to signup in to hoppscotch

### Environment

Production

### Version

Self-hosted

### PR DESCRIPTION
**Pull request by domestic-fennec**
Closes #3050 #3139 

### Description (bugfix)
The `passReqToCallback=true` alters the arguments passed to `MicrosoftStrategy.validate` such that first argument is a `request` object and other arguments are shifted across one. This meant that actual values for `accessToken` and critically `profile` weren't in the expected arguments and therefore the rest of the method would break. I believe `passReqToCallback` was added in error in 81cb0d43d78e41a3ce1e82260a10fa9baedfbc64. This method could never work in it's current form with this option set to true.

This has been tested (and previously debugged) on a private instance of hopscotch so I can confirm that this method does now indeed work in "production"

###  Description (feature)

Many orgs using Azure AD will be running on their own "tenants" rather than the "common" tenant, and therefore need to be able to specify a tenant ID to allow oauth2 url's to be correctly generated by passport-microsoft. This change allows setting the tenant ID as the `MICROSOFT_TENANT` env var.

See passportjs.org/packages/passport-microsoft for more detail.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### Additional Information
none

### CODE REVIEW

**Comment by henrysachs** [comment]
Hey, I would greatly appreciate if we can merge this. Maybe @AndrewBastin can take a look at the missing workflow? does it need to be approved by you?

**Comment by AndrewBastin** [comment]
@henrysachs  Yep, we are hoping to get this done as well, just backslid a bit with all the PRs open and stuff.

Since we don't use AD ourselves, we are not sure how we can exactly confirm this works, so we were reaching out to the community to help review this.

If you want @henrysachs, you can help us out and see if this fixes issues for you in AD.

**Comment by henrysachs** [comment]
ah okay then I misunderstood the PR Status. I can try to get a local setup working and test this.

**Comment by henrysachs** [comment]
Hi there I managed to login with the parameter but the api logged an error:

```text
hoppscotch-backend              | [Nest] 19  - 06/21/2023, 12:35:34 PM   ERROR [ExceptionsHandler] user_settings/not_found
hoppscotch-backend              | Error: user_settings/not_found
hoppscotch-backend              |     at throwErr (/usr/src/app/dist/utils.js:13:11)
hoppscotch-backend              |     at UserSettingsResolver.updateUserSettings (/usr/src/app/dist/user-settings/user-settings.resolver.js:42:34)
hoppscotch-backend              |     at async target (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)
hoppscotch-backend              |     at async Object.updateUserSettings (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
hoppscotch-backend              | Query Complexity: 2
hoppscotch-backend              | Query Complexity: 2
hoppscotch-backend              | Query Complexity: 7
hoppscotch-src-hoppscotch-db-1  | 2023-06-21 12:35:34.870 UTC [33] ERROR:  duplicate key value violates unique constraint "UserSettings_userUid_key"
hoppscotch-src-hoppscotch-db-1  | 2023-06-21 12:35:34.870 UTC [33] DETAIL:  Key ("userUid")=(clj5p6hlz0000pb0jct996uur) already exists.
hoppscotch-src-hoppscotch-db-1  | 2023-06-21 12:35:34.870 UTC [33] STATEMENT:  INSERT INTO "public"."UserSettings" ("id","userUid","properties","updatedOn") VALUES ($1,$2,$3,$4) RETURNING "public"."UserSettings"."id"
hoppscotch-backend              | [Nest] 19  - 06/21/2023, 12:35:34 PM   ERROR [ExceptionsHandler] user_settings/settings_already_exists
hoppscotch-backend              | Error: user_settings/settings_already_exists
hoppscotch-backend              |     at throwErr (/usr/src/app/dist/utils.js:13:11)
hoppscotch-backend              |     at UserSettingsResolver.createUserSettings (/usr/src/app/dist/user-settings/user-settings.resolver.js:36:34)
hoppscotch-backend              |     at async target (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)
hoppscotch-backend              |     at async Object.createUserSettings (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
```

for me as a "user" this wasn't noticeable

**Comment by balub** [comment]
@henrysachs could you let me know when you encountered this error?

**Comment by balub** [comment]
@henrysachs when you say noticeable do you mean you were not shown any indications in the hopscotch app of these errors, but other than that did everything else mainly the Microsoft auth function properly?

**Comment by henrysachs** [comment]
@balub exactly what you are describing the app works as expected :)

**Comment by balub** [comment]
@henrysachs Those are known, what is important is that the Microsoft auth works.

**Comment by henrysachs** [comment]
It is so I think thats fine for merging :)

**Review by balub — APPROVED** [review]

**Comment by balub** [comment]
Thanks for the contribution @domestic-fennec and @henrysachs.

**Pull request merged**
