### PR TITLE
Add Response examples to a request

### LINKED ISSUE #1875: [feature]: Ability to save API response
**Is your feature request related to a problem? Please describe.**
I would like to be able to save an API response similar to the feature in postman. 
1. This will then allow us to preview the API instead of having to do a request to get the response. 
2. Also this is helpful whereby if you use a token to authenticate and the token has expired, instead of reauthenticate to view a response you get to quickly see the structure and response of the API.

**Describe the solution you'd like**
The solution for this is when a request to an API has returned a result we have a new button to save the response. This would be nested under the saved API request. 
We should be able to rename the saved response as there could be different responses from 1 request. e.g if an exception was raised in the api we could receive a different response.

**Describe alternatives you've considered**
At the moment the only alternative is to save the response in a file locally, but this is very hectic and not easily sharable to other people in the team as we may have a long list of 100 APIs. 

**Additional context**
Postman seem to have done it very well.

### PR DESCRIPTION
**Pull request by codeasashu**
Closes #1875 

### Description
Since [1894](https://github.com/hoppscotch/hoppscotch/pull/1894) has gone stale, I've decided to revamp the feature once again. My main motivations are:
1. Save common useful responses to a request
2. This is a prerequisite to support openapi export (#3821)
3. Ability to edit and share responses along with request, provides more fulfilling API experiences

- [x] Save responses of request
- [x] Rename, delete and edit saved responses
- [x] Import responses from postman collection
- [ ] Import responses from openapi
- [x] Export responses

### Checks
- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by codeasashu** [comment]
@thetronjohnson Thank you for responding. Yes, examples (or saved responses) are essentially a part of documentation. 

Curious to know if the API Docs you're working on, is compatible with openapi? We've been waiting [long](https://github.com/hoppscotch/hoppscotch/issues/2018) [enough](https://github.com/hoppscotch/hoppscotch/pull/1894#issuecomment-1077452643) for this to land, so I am not expecting much. I just want to be able to share my hoppscotch collection and tell how 200 and 404 will look like. Waiting for 3 years to be able to document such seemingly simple thing is just out of scope for me (no offense, the tool is still great).

I've already made converters for [postman](https://github.com/codeasashu/openman) and [insomnia](https://github.com/codeasashu/insomnia-oas-converter), so this one shouldn't be hard. I feel supporting openapi would open endless possibilities, due to the large ecosystem it supports.

Not expecting this to land in mainstream anytime soon, but can't wait on promises no more.

**Comment by thetronjohnson** [comment]
@codeasashu yes it will be compatible with OpenAPI 💯

**Comment by codeasashu** [comment]
@thetronjohnson Awesome!!! Finally a great news. Do you have any ETA/Roadmaps? Is it already in any sprint goals for this year? I'll be super happy to contribute in any way. Let me know if this can be prioritised.

**Comment by Scorpions777** [comment]
I need this feat

**Comment by codeasashu** [comment]
@Scorpions777 Please +1 the original description instead

**Comment by codeasashu** [comment]
Hello @thetronjohnson, are you EVER going to prioritise this? You didn't allowed me to proceed, neither did you guys managed to get this done.

This tells how much of low priority documentations are, for you guys. While I can't stress enough how important documentations are, before even writing a single line of API code, the reacts on the PR is proof enough. Yet, nothing is being done in this regards, neither is there any ETA. 

I hope this time you guys will prioritise this. Otherwise, I am going to go ahead an implement it myself.

**Comment by thetronjohnson** [comment]
hi @codeasashu we had already released the feature to save responses to a collection in our September 2024.9.0 release
https://hoppscotch.com/blog/hoppscotch-v2024-9-0 :)

**Comment by caturbgs** [comment]
> hi @codeasashu we had already released the feature to save responses to a collection in our September 2024.9.0 release
> 
> https://hoppscotch.com/blog/hoppscotch-v2024-9-0 :)

This should close this issue then

**Comment by codeasashu** [comment]
@caturbgs Yes, this fixes it. Closing the issue

**Pull request closed without merging**
