### PR TITLE
fix: update vite-plugin-dts version which fixes build issue on docker/alpine

### PR DESCRIPTION
**Pull request by anwarulislam**
Closes HFE-57 #2999 

## Description

- This PR updates `vite-plugin-dts` packages version to `3.2.0`. The previous version was having issues building the `hoppscotch-ui` package.
- Updated `Anchor.vue` component to `setup` script

### CODE REVIEW

**Review by amk-dev — CHANGES_REQUESTED** [review]
Seems like the vite-plugin-dts has some breaking changes in version 3. can you check out vite.config.ts and see if we're using them. its showing some type errors.

**Comment by AndrewBastin** [comment]
@amk-dev please re-review.

**Review by amk-dev — APPROVED** [review]
LGTM

**Review by liyasthomas — APPROVED** [review]
LGTM 💯

**Pull request merged**
