### PR TITLE
fix: search panel position in response

### PR DESCRIPTION
**Pull request by khusroohayat**

### CODE REVIEW

**Comment by khusroohayat** [comment]
@anwarulislam please review this for issue [](https://github.com/hoppscotch/hoppscotch/issues/2459)

**Review by anwarulislam — COMMENTED** [review]
Hi @khusroohayat, It's working fine. it's better instead of shown in the footer. can you make this sticky as well while scrolling to bottom?

**Comment by khusroohayat** [comment]
@anwarulislam we already have a Json Outline showing it in bottom thats why i moved it to top

**Comment by anwarulislam** [comment]
> @anwarulislam we already have a Json Outline showing it in bottom thats why i moved it to top

Yeah, that looks good. We'll keep it on top. I said to make it fixed when scrolling. Now, it's relative to the content

**Comment by khusroohayat** [comment]
> > @anwarulislam we already have a Json Outline showing it in bottom thats why i moved it to top
> 
> Yeah, that looks good. We'll keep it on top. I said to make it fixed when scrolling. Now, it's relative to the content

Ok doing it, thanks

**Review by anwarulislam — APPROVED** [review]

**Comment by anwarulislam** [comment]
@liyasthomas it looks good to me. we can merge it.

**Comment by liyasthomas** [comment]
@khusroohayat thanks for this quick fix. I've updated the style to CSS variable for better UI consistency.

**Review by liyasthomas — APPROVED** [review]
LGTM 💯

**Pull request merged**
