### PR TITLE
feat: loading states for modal buttons

### PR DESCRIPTION
**Pull request by kyteinsky**
### Description

Adds loading state to buttons in different modals.

### CODE REVIEW

**Comment by kyteinsky** [comment]
`SmartConfirmModal` would need modifications if delete functionality also needs loading.

**Review by AndrewBastin — APPROVED** [review]
lgtm :100:

ask and wait for @liyasthomas to know whether we should do anything about the Delete option.

Although, I would think it will not hurt to do that.

**Comment by liyasthomas** [comment]
@kyteinsky it would be great if we can introduce loading state in delete confirmation modals too. Mainly the delete request, delete collection, delete folder prompts on teams.

**Comment by kyteinsky** [comment]
@liyasthomas There are two ways to add loading in delete confirmation modals, one by introducing an optional prop in `SmartConfirmModal` and the other by creating a new component altogether. Which path should I take?

**Comment by liyasthomas** [comment]
Introduce a prop in `SmartConfirmModal` will be the best way to do it.

**Comment by kyteinsky** [comment]
Should I change the Folder delete logic in the respective files `CollectionMyFolder` and `CollectionTeamsFolder` or move them to `index.vue`? Or maybe move the delete functions for Request and Collection to their respective files?

**Comment by AndrewBastin** [comment]
@kyteinsky you can maintain whatever way it is right now and not worry about where the logic is (although, all of them should be in index.vue). We are planning a major rewrite of the collection tree structure and we will clear most of it during that time.

**Review by AndrewBastin — APPROVED** [review]
lgtm 💯

**Pull request merged**
