### PR TITLE
i18n: Improve Chinese (Simplified and Traditional) translations

### PR DESCRIPTION
**Pull request by jks15satoshi**
I try my best to improve the Chinese translations. Although not all the entries are translated, I think it's enough to be used for Chinese users. It could be better, of course.

### CODE REVIEW

**Review by liyasthomas — APPROVED** [review]
@jks15satoshi Thanks for this quick PR. Really appreciate it.

**Comment by jks15satoshi** [comment]
> @jks15satoshi Thanks for this quick PR. Really appreciate it.

My pleasure.

**Comment by liyasthomas** [comment]
Translations are updated once every week.

**Comment by jks15satoshi** [comment]
> Translations are updated once every week.

Got it, thanks!

**Pull request merged**
