### PR TITLE
Add search input & capability to graphql types and fields

### PR DESCRIPTION
**Pull request by LeoMartinDev**
Related issue #1188 

The PR adds basic filtering for `queryFields`, `mutationFields`, `subscriptionFields` and `gqlTypes`.

The value provided to the search input is used to match on `fieldName` and `description` fields.

`gqlTypes` are handled differently as we also filter on `gqlTypes._fields` array.

Some improvements for an other PR could be to highlight matched text (?)
Also, `gqlTypes._fields` filtering could be improved by keeping only matched fields as it can be confusing to see the whole Schema and having to scroll until you find concerned field

**Unfiltered results**

image

**Filtered results**

image

### CODE REVIEW

**Comment by AndrewBastin** [comment]
@LeoMartinDev congrats on your first contribution to Hoppscotch!!!!

This is really good stuff!

Umm, the types search is a bit confusing for now. But we are sorta thinking of a overhaul to the GraphQL page anyways. To make it a lot more simplified.

To solve the issue with types search for now, can we highlight matched fields with an outline or some color effect ? If you are able to pull that off too, this would be perfect, or I will eventually come around and implement that.

**Comment by LeoMartinDev** [comment]
> @LeoMartinDev congrats on your first contribution to Hoppscotch!!!!
> 
> This is really good stuff!
> 
> Umm, the types search is a bit confusing for now. But we are sorta thinking of a overhaul to the GraphQL page anyways. To make it a lot more simplified.
> 
> To solve the issue with types search for now, can we highlight matched fields with an outline or some color effect ? If you are able to pull that off too, this would be perfect, or I will eventually come around and implement that.

Thanks, glad to help 😄 
I thought about the highlighting feature and I have two solutions :
1. creating a new prop `hightlight-name` to the `field` component and set it to `true` from the graphql page
2. add a new key to the `grapqlTypes._fields` like `{ fieldNameToDisplay: '<span class="highlighted">Test</span>' }` and render it using `v-html`

**Comment by AndrewBastin** [comment]
The first one seems better.

**Comment by LeoMartinDev** [comment]
@liyasthomas I just added the highlighting functionality, any thought about the styling ? For now the text is just yellow 😅

image

**Comment by liyasthomas** [comment]
I'll look into it.

**Review by liyasthomas — APPROVED** [review]
LGTM

cc: @AndrewBastin

**Pull request merged**
