### PR TITLE
feat: clone folder for my collection

### PR DESCRIPTION
**Pull request by TheHollidayInn**
Closes # 

### Description

Duplicate folder for my collection to duplicate folder: #2475

If this is good, I can work on the duplicate for my team.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### Additional Information

Screen Shot 2022-10-16 at 7 30 12 AM

### CODE REVIEW

**Comment by AndrewBastin** [comment]
We are keeping this PR in hold until we have a clone implementation on the backend for supporting Teams as well.

@TheHollidayInn I hope you have turned on, "Allow edits from maintainers" on this PR.

Thank you for your contribution  ^_^

**Comment by prom00** [comment]
What is holding this feature back at the moment? Would be nice if this could be added. This is quite a basic function which is often used when creating CRUD endpoints for a REST api. You always need 5 endpoints and all should be using authorization and often also headers.

Would be nice if we could just duplicate folders.

**Comment by mbmohib** [comment]
Hi, is there any update on this?

Duplicating every single request is pretty annoying.

**Comment by jamesgeorge007** [comment]
Hi, thanks for the PR. Support for duplicating collections has been implemented in #4211 and released in [v2024.7.0](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.7.0). Hence, closing this PR.

**Pull request closed without merging**
