### PR TITLE
feat: add client credentials

### PR DESCRIPTION
**Pull request by mdbetancourt**
Closes https://github.com/hoppscotch/hoppscotch/issues/874

### Description
Add client credential to oauth2

### Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by liyasthomas** [comment]
Hi @mdbetancourt, thank you for this quick PR, appreciate your interest in contributing to Hoppscotch.

Can you provide a screen record of this new addition - may be a success and failed case with `clint credentials`. This will help us to review the PR and merge it into production faster.

**Comment by AndrewBastin** [comment]
Closing due to being stale and no response.

**Comment by bram-pkg** [comment]
@mdbetancourt this would be really nice

**Comment by lordvlad** [comment]
Would be nice to have this :+1:

**Comment by lordvlad** [comment]
I pulled some changes from this branch into #3298 and updated the UI

**Pull request closed without merging**
